version: '3'

services:

  server:
    build: .
    image: ${DOCKER_REGISTRY}/ansible_server
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    hostname: ansible
    networks:
      automation-network:
        aliases:
          - ansible

networks:
  automation-network:
    external: true
